/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Display: typeof import('./src/components/Display.vue')['default']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    ParameterView: typeof import('./src/components/ParameterView.vue')['default']
    ResultTable: typeof import('./src/components/ResultTable.vue')['default']
  }
}
